# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'


    #normalizer
    get_set_method_normalizer:
      class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
      public: false
      tags: [serializer.normalizer]


  #elarning User
    FediBundle\Repository\UserRepository:
      class: 'FediBundle\Repository\UserRepository'
      autowire: true
      public: true
      tags: ['doctrine.repository_service']


    #elarning reository
    FediBundle\Repository\ElearningSessionRepository:
            class: 'FediBundle\Repository\ElearningSessionRepository'
            autowire: true
            public: true
            tags: ['doctrine.repository_service']


    #Media Elearnin repository
    FediBundle\Repository\ElearningSessionMediasRepository:
            class: 'FediBundle\Repository\ElearningSessionMediasRepository'
            autowire: true
            public: true
            tags: ['doctrine.repository_service']

    #Formation  repository
    FediBundle\Repository\FormationRepository:
      class: 'FediBundle\Repository\FormationRepository'
      autowire: true
      public: true
      tags: ['doctrine.repository_service']

     #User elearning

    FediBundle\Repository\UserElearningSessionRepository:
          class: 'FediBundle\Repository\UserElearningSessionRepository'
          autowire: true
          public: true
          tags: ['doctrine.repository_service']

  #Question

    FediBundle\Repository\QuestionRepository:
      class: 'FediBundle\Repository\QuestionRepository'
      autowire: true
      public: true
      tags: ['doctrine.repository_service']





