fedi_homepage:
    path:     /
    defaults: { _controller: FediBundle:Default:index }

fedi_Questionpage:
    path:     /Question/
    defaults: { _controller: FediBundle:Question:index }

fedi_AjouterQuestion:
    path:    /Question/ajouterques
    defaults: { _controller: FediBundle:Question:newQuestion }
    methods: [post,get]

fedi_EditerQuestion:
    path:     /Question/{id}/Edit
    defaults: { _controller: FediBundle:Question:edit }
    methods: [post,get]



fedi_StatusQuestion:
    path:     /Question/{id}/statusQuestion
    defaults: { _controller: FediBundle:Question:statusQuestion }

fedi_DeleteQuestion:
    path:     /question/{id}/delete
    defaults: { _controller: FediBundle:Question:delete }

fedi_Formationpage:
    path:     /Formationlist
    defaults: { _controller: FediBundle:Formation:index }


fedi_AjouterFormation:
    path:     /AjouterFormation
    defaults: { _controller: FediBundle:Formation:newFormation }

fedi_EditerFormation:
    path:     Formation/{id}/EditerFormation
    defaults: { _controller: FediBundle:Formation:edit }


fedi_StatusFormation:
    path:      /{id}/statusFormation
    defaults: { _controller: FediBundle:Formation:status }


fedi_DeleteFormation:
    path:      Formation/DeleteFormation/{id}
    defaults: { _controller: FediBundle:Formation:delete }

fedi_AjouterMedia:
    path:     /AjouterMedia
    defaults: { _controller: FediBundle:Medias:newMedia }


fedi_MediaQuiz:
    path:     /MediaQuiz
    defaults: { _controller: FediBundle:Medias:listMediasQuiz }

fedi_MediaElearning:
    path:     /MediaEle
    defaults: { _controller: FediBundle:Medias:listMediasEl }

fedi_DeleteMedia:
    path:     /DeleteMedia/{id}
    defaults: { _controller: FediBundle:Medias:delete }

fedi_EditMedia:
    path:     /EditMedia/{id}
    defaults: { _controller: FediBundle:Medias:edit }

fedi_Levelpage:
    path:     /Levelpage
    defaults: { _controller: FediBundle:Level:index }

fedi_ajoutlevel:
    path:     /ajoutLevel
    defaults: { _controller: FediBundle:Level:newLevel }

fedi_editlevel:
    path:     /editlevel/{id}
    defaults: { _controller: FediBundle:Level:editLevel }

fedi_newEle:
    path:     /newElee
    defaults: { _controller: FediBundle:ElearningSession:newSession }

list_Ele:
    path:     /listElearning
    defaults: { _controller: FediBundle:ElearningSession:index }

modifier_Ele:
    path:     /modifElee/{id}
    defaults: { _controller: FediBundle:ElearningSession:edit }

Delate_Ele:
    path:     /delateEla/{id}
    defaults: { _controller: FediBundle:ElearningSession:delete }

formationEle_by_level:
    path:     /formationElebylevel/{idLev}
    defaults: { _controller: FediBundle:ElearningSession:getSessionByLevel }
    options: [expose]

liste_eleve_afecte:
    path:     /liste_eleve_affecté
    defaults: { _controller: FediBundle:EleveFormation:ListElevetElearningSession}

afect_Form:
    path:     /affecter_eleve
    defaults: { _controller: FediBundle:EleveFormation:affecteEleveElearningSession}
Eleve_list:
    path:     /list
    defaults: { _controller: FediBundle:EleveElearningSession:listSessionsEl }

filter_by_Lvel:
    path:    /list/by-level/{$idle}
    defaults: { _controller: FediBundle:EleveElearningSession:FiltreSessionsElearningByLevel}
    options: [expose]



filter_by_Formation:
    path:    /list/{id}
    defaults: { _controller: FediBundle:EleveElearningSession:FiltreSessionsElearningByLevel}
    methods: [post]

detail_bysession:
    path:    /details/{idSession}
    defaults: { _controller: FediBundle:EleveElearningSession:DetailFormationBySession}

Quiz:
    path:     /Quiz/{idSession}
    defaults: { _controller: FediBundle:EleveElearningSession:quiz}

get_ALL_Formation:
    path:     /getallformation
    defaults: { _controller: FediBundle:Formation:getallFormation}
    methods: [post,get]

get_ALL_Level:
    path:     /getalllevel
    defaults: { _controller: FediBundle:Level:getalllevel}
    methods: [post,get]


get_ALL_question :
    path:     /getallQuestion
    defaults: { _controller: FediBundle:Question:getallquestion}
    methods: [post,get]

get_ALL_media :
    path:     /getalllmedia
    defaults: { _controller: FediBundle:Medias:getallmedia}
    methods: [post,get]






